### ISSUE TITLE
Cannot multiply after "keep lowest" (`4d6l2X`)

### ISSUE THREAD

**Issue by bmarwell** [diceroll-dev/dice-parser#55]
Imagine you want to multiply two dice: `2d6X`.

But I want four dice thrown and multiply only the LOWEST values:
`4d6l2` will keep two dice of four, but where to add the `X` now?
`4d6l2X` will result in:

```
org.jboss.resteasy.spi.UnhandledException: dev.diceroll.parser.ParseException: Failed to parse expression '4d6l2X'
at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
at [internal classes]
Caused by: dev.diceroll.parser.ParseException: Failed to parse expression '4d6l2X'
at dev.diceroll.parser.impl.RegexDice.parse(RegexDice.kt:102)
at dev.diceroll.parser.impl.RegexDice.visitAdd(RegexDice.kt:171)
at dev.diceroll.parser.impl.RegexDice.access$visitAdd(RegexDice.kt:20)
at dev.diceroll.parser.impl.RegexDice$parsers$21.invoke(RegexDice.kt:86)
at dev.diceroll.parser.impl.RegexDice$parsers$21.invoke(RegexDice.kt:86)
at dev.diceroll.parser.impl.RegexDice.parse(RegexDice.kt:104)
at dev.diceroll.parser.impl.RegexDice.visitAdd(RegexDice.kt:170)
at dev.diceroll.parser.impl.RegexDice.access$visitAdd(RegexDice.kt:20)
at dev.diceroll.parser.impl.RegexDice$parsers$21.invoke(RegexDice.kt:86)
at dev.diceroll.parser.impl.RegexDice$parsers$21.invoke(RegexDice.kt:86)
at dev.diceroll.parser.impl.RegexDice.parse(RegexDice.kt:104)
at dev.diceroll.parser.Dice.detailedRoll(Dice.kt:27)
at de.bmarwell.dicerollparser.rest.resource.DiceResource.rollObject(DiceResource.java:26)
at de.bmarwell.dicerollparser.rest.resource.DiceResource$Proxy$_$$_WeldClientProxy.rollObject(Unknown Source)
```

**Comment by bmarwell** [comment]
Interestingly, `4d6l2asc` will work, but it will not only reorder the 4d6l2, but also others added using `+`. Will open another issue :)
